### PR TITLE
Typos, Grammar, OCDness

### PR DESCRIPTION
**Pull request by noplanman**
Regarding the "authenticated user" texts, there was a mix and I've opted to go for "currently authenticated user", as it kind of makes more sense in the scheme of things.

Let me know if I should change them to just "authenticated user" :smiley:

All other changes should be self explanatory.

### CODE REVIEW

**Comment by skyschub** [comment]
Could you please squash your commit into one or at least change the wording of the commits? "Just some OCDness, that's all" is not very descriptive...

**Comment by noplanman** [comment]
Sure thing, but I need your help with this if that's ok.

How can I squash the commits so that they appear on this PR as a single commit only?
Is that even possible or must I create a new PR?

**Comment by noplanman** [comment]
Ok cool, I found out how.
Is this better?

**Comment by skyschub** [comment]
Yeah, thanks.

**Pull request merged**
